/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DATE 0x09160522
#define DATE_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETDATE 1
extern  long * getdate_1(void *, CLIENT *);
extern  long * getdate_1_svc(void *, struct svc_req *);
extern int date_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETDATE 1
extern  long * getdate_1();
extern  long * getdate_1_svc();
extern int date_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATE_H_RPCGEN */
